<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_India 91</name>
   <tag></tag>
   <elementGuidId>c6af0d06-4b2f-4754-bdb4-d3b2ca0ccfce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth-country-picker_92</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='auth-country-picker_92']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>838b8609-1b54-4d42-9e7f-cd7f1197c5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>745aba9b-2a5b-4119-82ef-8722b87abbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>c2a06e3f-da7c-456f-b3c3-a7476943716e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;IN&quot;}</value>
      <webElementGuid>d4718414-146d-4049-a9fc-69610566b38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-country-picker_92</value>
      <webElementGuid>d5ab1bb5-ca85-4b4d-b55d-a51df3d58c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>b7ffe1e3-6e2f-4e3d-ad58-3c94fcfc1d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>India +91</value>
      <webElementGuid>34996993-6f3d-4e67-b2c2-fa14463c28e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-country-picker_92&quot;)</value>
      <webElementGuid>ea77c7d6-caee-46a3-aa86-7319f7fcd42c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='auth-country-picker_92']</value>
      <webElementGuid>46bd1c42-0bab-4279-b188-72332d8630ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-1']/div/div/ul/li[93]/a</value>
      <webElementGuid>3365682a-bdb8-46f5-a3ee-c67feddc489a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[93]</value>
      <webElementGuid>c1a43930-e1d2-4a5e-862b-59e198b47f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[93]/a</value>
      <webElementGuid>392d670e-0a53-427b-b2b7-39aa8495e712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'auth-country-picker_92' and (text() = 'India +91' or . = 'India +91')]</value>
      <webElementGuid>eb758f73-9629-489e-91d6-a92da3494d8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
