<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_customerName</name>
   <tag></tag>
   <elementGuidId>5d42cea3-a33c-4624-bf1c-ffc5c9c4c4cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ap_customer_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53d73f60-6f7c-4ad5-ab1a-1b5137e898b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f1c0541-b5ec-4aa4-887f-cb9d8e3f439b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>140350f3-5fcd-4c95-b7b8-8dd4d44245f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ap_customer_name</value>
      <webElementGuid>878bef5e-855f-4347-900e-944c81e728ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>f85f6590-b472-4558-a9e0-b3df46289cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First and last name</value>
      <webElementGuid>b9f45c24-5566-42e2-8536-bce3a345d3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerName</value>
      <webElementGuid>e5ead5d1-7300-4fd0-9e03-ed782e876996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d1f72743-9746-4b3e-b83f-eb4edd2b9b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-span12 auth-autofocus auth-required-field</value>
      <webElementGuid>33c7f36f-4262-4af2-9bcd-8c07716ffe90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap_customer_name&quot;)</value>
      <webElementGuid>99f240c7-e225-4f44-b7bb-bee15bcab213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ap_customer_name']</value>
      <webElementGuid>8dc49ec6-e11c-49a6-b152-c7c478d5c49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ap_register_form']/div/div/div/input</value>
      <webElementGuid>da86038d-a5f0-4d8a-a741-68477f5b2941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>4257cb28-c365-45c7-aa5f-de9822608164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ap_customer_name' and @placeholder = 'First and last name' and @name = 'customerName']</value>
      <webElementGuid>8f7a73d2-1dc7-4dfd-acd9-e6f70956a1e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
