<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hello, sign in</name>
   <tag></tag>
   <elementGuidId>a8fbef6a-ead4-4715-a785-6c57f43f9d28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-link-accountList-nav-line-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='nav-link-accountList-nav-line-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b5c5ebc5-81cc-4113-947b-6b1e686086df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-link-accountList-nav-line-1</value>
      <webElementGuid>fd86bc6f-915f-4b93-b9b5-eb2b5d6cb23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-line-1 nav-progressive-content</value>
      <webElementGuid>cb2dfa37-cb61-4194-8b3e-fb05faf42053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hello, sign in</value>
      <webElementGuid>5c277b1c-7a31-46b0-8543-32958d76e875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-link-accountList-nav-line-1&quot;)</value>
      <webElementGuid>20b65bad-4f0d-4799-bb00-695c9e792944</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='nav-link-accountList-nav-line-1']</value>
      <webElementGuid>b9a3d4df-67f4-457e-8acc-77a86e6cf039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nav-link-accountList']/div/span</value>
      <webElementGuid>d6b53e08-d91a-447c-b2b7-d8974365ce72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/span</value>
      <webElementGuid>d1ba8012-b119-4161-8a8b-ee1114585676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'nav-link-accountList-nav-line-1' and (text() = 'Hello, sign in' or . = 'Hello, sign in')]</value>
      <webElementGuid>c82e680e-881b-4c03-8570-1df4d7801467</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
