<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>11c0b005-a1e9-467e-aec9-b06665282938</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ap_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ap_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b28ec26d-c3de-4287-9b5a-22d17d25e5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>78ee861c-bafb-4c51-8f45-a07f4e9559bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>1612b90a-b9cf-49f4-93df-c5814c28941b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ap_password</value>
      <webElementGuid>596d0490-f489-48d1-8b10-5b615c922557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>85963294-b9a6-45ed-86e6-7b0628bf4f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>At least 6 characters</value>
      <webElementGuid>1590695b-f143-4ffe-bf2c-496e5b4a9263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8fe3d181-dd31-4c22-93bb-53bb2e4a979c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>26a405ce-14be-4913-a4ce-04c7b40c238b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-span12 auth-required-field auth-require-fields-match auth-require-password-validation</value>
      <webElementGuid>70a743f3-0c59-4416-bec8-1629f92455e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap_password&quot;)</value>
      <webElementGuid>a33dd9b0-a783-44de-8f86-02e1c7878fd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ap_password']</value>
      <webElementGuid>742518fa-65ce-496f-856f-ab867f89aaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ap_register_form']/div/div/div[3]/div/input</value>
      <webElementGuid>281fa78f-0a53-4e36-bf3c-1afd34d061c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>85751c74-c45a-4b0a-9211-c81c83f23a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'ap_password' and @placeholder = 'At least 6 characters' and @name = 'password']</value>
      <webElementGuid>9717ec14-4f84-4289-b131-64c76cc62dbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
