<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_nav-cart-icon nav-sprite</name>
   <tag></tag>
   <elementGuidId>d54c36dc-0b38-45c8-8852-2992ff2158e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.nav-cart-icon.nav-sprite</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-cart-count-container']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>154b2949-2db8-464f-a2f4-b797baa6c66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-cart-icon nav-sprite</value>
      <webElementGuid>f90737c2-5059-47df-8a57-da51e75f5a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-cart-count-container&quot;)/span[@class=&quot;nav-cart-icon nav-sprite&quot;]</value>
      <webElementGuid>64a7f866-3e20-45f0-b7a6-d4a935ae5390</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-cart-count-container']/span[2]</value>
      <webElementGuid>b0e52ef7-c43a-44bf-9c16-18c41b6c23fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div/span[2]</value>
      <webElementGuid>c53a3620-2621-4967-b0a2-ae68d92ca0c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
