<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_proceedToRetailCheckout</name>
   <tag></tag>
   <elementGuidId>5715000b-30ba-452a-9b09-c3f81ad2bd4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;proceedToRetailCheckout&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c6de84e-1ddd-466c-aa5e-c0b1d4c31374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>proceedToRetailCheckout</value>
      <webElementGuid>1ae68295-1859-4da4-b4bc-e6070e23cf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feature-id</name>
      <type>Main</type>
      <value>proceed-to-checkout-action</value>
      <webElementGuid>4d75542b-3732-416a-8db2-90cce9445c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>07e5f161-28de-4ce3-9036-12e829f6a2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>63dfdc79-72aa-4cfc-b47c-f825528ace21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Proceed to checkout</value>
      <webElementGuid>a3663937-3cd2-44a6-8bf8-004df13f2dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>sc-buy-box-ptc-button-announce</value>
      <webElementGuid>df57f44d-3c20-4e24-ae93-ae1b01f4e760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-buy-box-ptc-button&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>a145a26d-9b11-4dde-9f1a-c16990aac748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='proceedToRetailCheckout']</value>
      <webElementGuid>a139fb94-ee91-46c3-b3da-595537196b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='sc-buy-box-ptc-button']/span/input</value>
      <webElementGuid>02584564-4bb4-41d5-89fa-77683abb18ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>25ecbb65-f2d8-46e8-8367-eeb584d6bc1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'proceedToRetailCheckout' and @type = 'submit']</value>
      <webElementGuid>a673a246-6808-4921-b373-ad6bf11e9b5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
