<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_gift-wrap</name>
   <tag></tag>
   <elementGuidId>18c35dc1-aebd-41ef-ad20-c38448452c56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gift-wrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gift-wrap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f4928e7-b34d-453a-a09d-eb04ec6582fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gift-wrap</value>
      <webElementGuid>0931cf78-381a-4284-838b-a207414a8f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ae1a14fc-db9a-4af7-9789-66675547cd04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gift-wrap</value>
      <webElementGuid>61e556bd-ca00-4085-9f7c-02c6d255d00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>bfebdda7-1c60-434f-aaf7-dff1e7df566d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gift-wrap&quot;)</value>
      <webElementGuid>9d5a2ffd-e65c-4635-8da5-ec0e75b46929</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gift-wrap']</value>
      <webElementGuid>6ab53de3-f4e8-4abc-8612-c59f46f788c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detailPageGifting_feature_div']/div/label/input</value>
      <webElementGuid>939f679c-c194-40ae-b8e9-300aba34e7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>4c114e7c-46f5-417c-89b3-c0653770e568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gift-wrap' and @type = 'checkbox' and @name = 'gift-wrap']</value>
      <webElementGuid>f3a20cfd-148c-4bcc-8a4c-3a6e9ab91255</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
